### ISSUE TITLE
`WebSocketContext` is wrong in `WebSocketHandler`

### ISSUE THREAD

**Issue by Xerxes-2** [omjadas/hudsucker#112]
Actually, I found that `WebSocketContext::ClientToServer` is server to client, and vice versa. Or perhaps I misunderstood the meaning.

**Comment by omjadas** [comment]
It appears you are correct. I have pushed a fix to main and will do a release in the coming days.

**Comment by omjadas** [comment]
Fixed in [v0.22.0](https://github.com/omjadas/hudsucker/releases/tag/v0.22.0). Thanks for reporting this.
