### ISSUE TITLE
Seems not work with Proxifier

### ISSUE THREAD

**Issue by Xerxes-2** [omjadas/hudsucker#116]
Tried both on Windows and Mac, for proxying a Electron-based game.
The connections are often unstable in both HTTP and WebSocket, and log shows `hudsucker: Failed to forward request: client error (Connect)` .
I have installed the CA as trusted CA and proxy works fine in browser.

**Comment by omjadas** [comment]
Could you share the code for your `HttpHandler` and `WebSocketHandler`?

**Comment by Xerxes-2** [comment]
OK, seems not a hudsucker issue. I fixed my code and it runs well on Windows.
But for Mac I still face a CA issue, always get `Failed to establish TLS connection: received fatal alert: UnknownCA`

**Comment by omjadas** [comment]
Can you confirm you have installed the CA cert as a trusted root?

**Comment by Xerxes-2** [comment]
SIP is blocking me from install the CA into `/System/Library/Keychains/SystemRootCertificates.keychain`, maybe I should consider disabling it.
Anyway, thank you for helping me.
