### ISSUE TITLE
I found that "text/event-stream;" type not send one by one, It send when all the content down

### ISSUE THREAD

**Issue by songjiachao** [omjadas/hudsucker#119]
![iShot_2024-06-03_19 07 15](https://github.com/omjadas/hudsucker/assets/70792885/0b5a893b-1de9-4399-bee2-e7e1eaa50389)

**Comment by omjadas** [comment]
Could you please provide your implementation of `HttpHandler`?

**Comment by songjiachao** [comment]
async fn handle_response(&mut self, _ctx: &HttpContext, mut res: Response<Body>) -> Response<Body> {
    res = decode_response(res).unwrap();
    let req = self.req().clone().unwrap();

    let body_mut = res.body_mut();
    let body_bytes: bytes::Bytes = body_mut.collect().await.unwrap_or_default().to_bytes();

    let output_response = ProxiedResponse::new(
      res.status(),
      res.version(),
      res.headers().clone(),
      body_bytes,
      chrono::Local::now().timestamp_nanos_opt().unwrap(),
      hosts::get_ip(req.uri().host().unwrap()),
    );

    self.set_res(output_response).send_output();

    res
  }

**Comment by omjadas** [comment]
Collecting the body will wait for all of the events to be received before continuing. That is why you are seeing all events being sent from the proxy to the browser in one go. If you want to inspect the response body, I would recommend streaming the body and inspecting each frame one at a time.

**Comment by songjiachao** [comment]
Thank you very much .  Can you help me how to streaming the body and inspecting each frame one at a time.

**Comment by omjadas** [comment]
One way would be to do something like this

```rust
use futures::StreamExt;
use http_body_util::{BodyStream, StreamBody};
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;

async fn handle_response(&mut self, _ctx: &HttpContext, res: Response<Body>) -> Response<Body> {
    let (tx, rx) = mpsc::channel(100);
    let (parts, body) = res.into_parts();
    let mut body = BodyStream::new(body);

    tokio::spawn(async move {
        while let Some(frame) = body.next().await {
            if let Ok(frame) = frame.as_ref() {
                // inspect frame
            }

            tx.send(frame).await.unwrap();
        }
    });

    Response::from_parts(parts, StreamBody::new(ReceiverStream::new(rx)).into())
}
```
