### ISSUE TITLE
[feature request]: Allow proxy to untrusted SSL certificate websites.

### ISSUE THREAD

**Issue by axxop** [omjadas/hudsucker#122]
Currently, it is not possible to proxy to websites that use untrusted SSL certificates. For example: `curl -x http://127.0.0.1:3000 -H 'host: google.com' https://157.240.31.35 -vv -k.` When this request goes through hudsucker, it returns a 500 status. I have temporarily solved this issue using a [change](https://github.com/omjadas/hudsucker/commit/e96132b691615f1e9d7227e8b900ad988f7325bb) . 

What kind of API implementation do you think would be acceptable?

**Comment by omjadas** [comment]
This is already possible by providing a custom hyper client using `with_client`.
