### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by naiping123123** [omjadas/hudsucker#124]
Hello,

I always get NET::ERR_CERT_AUTHORITY_INVALID or timeouts when trying HTTPS websites.
Is there anything I have to change/add ?

Thanks

**Comment by naiping123123** [comment]
According to the sample code you provided, I still get a 502 error after using your certificate




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "omjadas/hudsucker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月13日(星期二) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [omjadas/hudsucker] SSL (Issue #124)





 
You will either have to install the CA cert as a trusted root on your device, or disable certificate checks in the program you are using (for Chrome that can be done with the --ignore-certificate-errors flag).

**Comment by omjadas** [comment]
Could you share your OS, OS version, browser, browser version and the website you are visiting? There should also be some logs to stdout, could you also share those?

**Comment by naiping123123** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "omjadas/hudsucker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [omjadas/hudsucker] SSL (Issue #124)





 
Could you share your OS, OS version, browser, browser version and the website you are visiting? There should also be some logs to stdout, could you also share those?

**Comment by naiping123123** [comment]
Microsoft Windows [版本 10.0.18363.1556]
Microsoft Edge版本 127.0.2651.98 (正式版本) (64 位)

The website you visit is a mock test site built by yourself, the certificate is generated by yourself, you can use GO as a proxy, but with your rust this is the error




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "omjadas/hudsucker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [omjadas/hudsucker] SSL (Issue #124)





 
Could you share your OS, OS version, browser, browser version and the website you are visiting? There should also be some logs to stdout, could you also share those?

**Comment by omjadas** [comment]
Sorry, did you mean to include the logs in your previous message?

**Comment by omjadas** [comment]
I believe this is the same as https://github.com/omjadas/hudsucker/issues/125
