### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by FynnFbc** [omjadas/hudsucker#130]
Request to add support for the Windows platform

**Comment by omjadas** [comment]
This should already work on Windows. Are you experiencing a specific issue?

**Comment by FynnFbc** [comment]
![image](https://github.com/user-attachments/assets/ed7fd5a9-bc02-4bfe-8260-01f38023673c)

**Comment by omjadas** [comment]
As the error message states, you will need to install OpenSSL if you want to use the OpenSSL CA.
