### ISSUE TITLE
How to generate CA cert

### ISSUE THREAD

**Issue by derust** [omjadas/hudsucker#18]
How to generate CA cert like [hudsucker.pem](https://github.com/omjadas/hudsucker/blob/main/examples/ca/hudsucker.pem)

It seems CA cert generate with [mkcert](https://github.com/FiloSottile/mkcert) doesn't work

thanks!

**Comment by derust** [comment]
Got it, thanks!
It seams I should waiting rustls ecosystem to be more mature to totally replace openssl.

**Comment by omjadas** [comment]
This should be fixed in [v0.11.1](https://github.com/omjadas/hudsucker/releases/tag/v0.11.1), which bumps https://github.com/est31/rcgen to 0.9
