### ISSUE TITLE
Offer to update readme with refering to other project

### ISSUE THREAD

**Issue by sinKettu** [omjadas/hudsucker#42]
Hello, @omjadas !
I maintain my own open source project, you can find it [here](https://github.com/sinKettu/cruster). My project relies on your library, so, first of all, I want to express my gratitude to you for this cool library.
I would like to offer you to refer my project in readme of yours (or in any other way) as example of software that uses your library. You also can find that I have already referred your project in readme of mine.
I believe that this can help me to find some contributors and keep improving the project.
I would appreciate any feedback.

**Comment by omjadas** [comment]
I have added a [Built With Hudsucker](https://github.com/omjadas/hudsucker#built-with-hudsucker) section to the README and included your project. Thanks for the suggestion!

**Comment by sinKettu** [comment]
Thank you so much!
