### ISSUE TITLE
Handle Specific Response?

### ISSUE THREAD

**Issue by venual** [omjadas/hudsucker#69]
I need to intercept a response from a specific url, I tried to do this multiple ways the only way I found was to get the request from the specific URL and then use reqwest copy the request<body> into a reqwest request then send it through reqwest client then convert the response to a hyper::Response<Body> then return req.into(), in Golang with mitmproxy-go this would be super simple id just match the URL and get the response easily, is there a better way to do this?

**Comment by omjadas** [comment]
You will want to store the URL in your handler while processing the `Request`. See https://github.com/omjadas/hudsucker/issues/67#issuecomment-1601869251 for how this can be done.
